package com.example.calkulator.calculator;

public enum Variants {
    OsnAndRevenueR,
    OsnAndIncome,
    OsnAndNDSObshay,
    OsnAndNDFL,
    OsnAndIncomeAndRevenueR,
    OsnAndIncomeAndNDSObshay,
    OsnAndIncomeAndNDFL,
    OsnAndIncomeAndRevenueRAndNDSObshayAndNDFL,
    OsnAndRevenueRAndNDSObshay,
    OsnAndRevenueRAndNDFL,
    OsnAndNDSObshayRAndNDNDFL,
    OooAndRevenueR,
    OooAndIncome,
    OooAndNDSObshay,
    OooAndNDFL,
    OooAndIncomeAndRevenueR,
    OooAndIncomeAndNDSObshay,
    OooAndIncomeAndNDFL,
    OooAndIncomeAndRevenueRAndNDSObshayAndNDFL,
    OooAndRevenueRAndNDSObshay,
    OooAndRevenueRAndNDFL,
    OooAndNDSObshayRAndNDNDFL,
    UsnAndRevenueR,
    UsnAndIncome,
    UsnAndNDSObshay,
    UsnAndNDFL,
    UsnAndIncomeAndRevenueR,
    UsnAndIncomeAndNDSObshay,
    UsnAndIncomeAndNDFL,
    UsnAndIncomeAndRevenueRAndNDSObshayAndNDFL,
    UsnAndRevenueRAndNDSObshay,
    UsnAndRevenueRAndNDFL,
    UsnAndNDSObshayRAndNDNDFL, Variants,
}
